### ISSUE TITLE
About the number '127.5' in this code

### ISSUE THREAD

**Issue by MrWhiteHomeman** [Edward-Lin/inpainting#2]
Hello,I have a question .
I know the size of images is 128 *128 in this code.
In this code, the 194th line of  inpaint.py : image_batch = (image_batch.astype(np.float32) - 127.5) / 127.5   
and the141th line of  utils.py :  image = image * 127.5 + 127.5.  
So, I want to know , is the number '127.5'   associated to the size of image? And if the size of my own images is 256 *360,  shall I change the number '127.5'?
I could appreciate it you can give me some advices.
Thank you ！！！

**Comment by Agent-INF** [comment]
127.5 = 255 / 2, and it means the average pixel value, since the range of each pixel value (8-bit) is 0 - 255. This is a simple normalization method, which maps all the pixel values to [-1, 1]. When saving an image to your disk, you should reverse this action(line 141).
Which means the value 127.5 is irrelevant to images size. You can also compute the average pixel value of your training dataset by each image channel before training, instead of simply using 127.5.

**Comment by MrWhiteHomeman** [comment]
Thank you！！！I know it.  Best  wish  to you ！！！
